name: Demo Workflow
on: workflow_dispatch
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print to Console
        run: echo Hello GH Actions!!!
      - name: Print a few line
        run: |
          echo First line!
          echo Second line!
